name: Build & Deploy ASP.NET Core to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLUTION_OR_PROJECT: './TooGoodToGo.sln'
      WEBAPP_PROJECT: 'TooGoodToGo/TooGoodToGo.csproj'
      PUBLISH_DIR: 'artifacts/publish'

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore $SOLUTION_OR_PROJECT

      - name: Build (Release)
        run: dotnet build $SOLUTION_OR_PROJECT --configuration Release --no-restore

      - name: Test
        run: dotnet test $SOLUTION_OR_PROJECT --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Publish WebApp only
        run: |
          rm -rf "$PUBLISH_DIR"
          mkdir -p "$PUBLISH_DIR"
          dotnet publish "$WEBAPP_PROJECT" -c Release -o "$PUBLISH_DIR"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: artifacts/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: app

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TooGoodToGo'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app
